server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  jpa:
    open-in-view: false

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always